from .base_page import BasePage
from .start_page import StartPage
from .main_menu_page import MainMenuPage
from .game_play_page import GamePlay
from .pause_overlay_page import PauseOverlayPage
from .get_another_chance_page import GetAnotherChancePage
from .settings_page import SettingsPage
from .store_page import StorePage
from .game_over_screen_page import GameOverScreen
